// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptionsTest {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD10oiiOiNlIw-qtU2kfzUByblygKl6ijM',
    appId: '1:1042736811024:web:86bf9fc78b8a83c09a0e95',
    messagingSenderId: '1042736811024',
    projectId: 'moviezapp-test',
    authDomain: 'moviezapp-test.firebaseapp.com',
    storageBucket: 'moviezapp-test.appspot.com',
    measurementId: 'G-RG0B7QSNB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN9GOy1JjeEKhRMkCWXyzrrI-6gQ2g_qo',
    appId: '1:1042736811024:android:2bd098c9dc7125f89a0e95',
    messagingSenderId: '1042736811024',
    projectId: 'moviezapp-test',
    storageBucket: 'moviezapp-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGKStbAVlpftjSYBDgBi7jiX1t-Cb3vxQ',
    appId: '1:1042736811024:ios:caab6937543e15e69a0e95',
    messagingSenderId: '1042736811024',
    projectId: 'moviezapp-test',
    storageBucket: 'moviezapp-test.appspot.com',
    iosClientId:
        '1042736811024-metmqd45s8shdsb11mtp7outp5pjecbp.apps.googleusercontent.com',
    iosBundleId: 'com.spverse.moviezapp',
  );
}
