const String kEmail = 'email';
const String kDisplayName = 'displayName';
// const String kTotalBooksMarkCount = 'totalBookMarksCount';
const String kBookMarkedMovieIdList = 'bookMarkedMovieIdList';
const String kBookMarkedShowIdList = 'bookMarkedShowIdList';
const String kCreatedDateTime = 'createdDateTime';
const String kMoviesCollection = 'movies';
const String kTvShowsCollection = 'tvShows';
const String kUsersCollection = 'users';
